# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: IntelCorporation.Intel(R)ExtremeTuningUtility
PackageVersion: 7.7.0.12
PackageLocale: en-US
Publisher: Intel Corporation
PublisherUrl: https://www.intel.com/
PublisherSupportUrl: https://www.intel.com/content/www/us/en/support.html
PrivacyUrl: https://www.intel.com/content/www/us/en/privacy/intel-privacy-notice.html
Author: Intel
PackageName: Intel(R) Extreme Tuning Utility
PackageUrl: https://www.intel.com/content/www/us/en/download/17881/intel-extreme-tuning-utility-intel-xtu.html
License: Intel Software License Agreement
Copyright: Copyright (c) Intel Corporation. All rights reserved.
CopyrightUrl: https://www.intel.com/content/www/us/en/legal/trademarks.html
ShortDescription: Intel(R) Extreme Tuning Utility
Description: Intel XTU is a Windows*-based performance-tuning software that enables novice and experienced enthusiasts to overclock, monitor, and stress a system. The software interface exposes a set of robust capabilities common in most enthusiast platforms along with new features available on new Intel® application processors and Intel® motherboards.
ReleaseNotes: https://downloadmirror.intel.com/29183/XTU-7.7.0.12-ReleaseNotes.pdf
ReleaseNotesUrl: https://downloadmirror.intel.com/29183/XTU-7.7.0.12-ReleaseNotes.pdf
ManifestType: defaultLocale
ManifestVersion: 1.1.0

